version: "3.7"

services:
  environ:
    image: wyx:LinuxDEV
    build:
      dockerfile: "./docker/LinuxDEV.Dockerfile"
      context: .
    stdin_open: true
    tty: true
    volumes:
        - "./workplace/:/root/workplace"
    ports:
      - "1234:1234"
      - "80:80"
      - "22:22"


